<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Verification code has been sent to 12345gmail.com. Please insert verification code to verify</name>
   <tag></tag>
   <elementGuidId>c1b44d17-4b95-446b-99ae-76f3610a6a15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-901oao.r-1vjbqqu.r-t1w4ow.r-ubezar.r-majxgm.r-135wba7.r-xyw6el.r-q4m81j.r-13qz1uu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[4]/div[2]/div/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e59dd0f0-a98b-467f-9002-97aa2e2ba2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>72de543b-2766-47e8-bb1b-ae183e020c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-1vjbqqu r-t1w4ow r-ubezar r-majxgm r-135wba7 r-xyw6el r-q4m81j r-13qz1uu</value>
      <webElementGuid>b01e9d79-e70a-4015-82f2-22290b6defaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verification code has been sent to 12345@gmail.com. Please insert verification code to verify.</value>
      <webElementGuid>759c61b8-9a90-485f-baab-86a0b01b08d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-1bwt9he&quot;]/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-txk6nv&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-13dzg4q r-1rttkqs&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-kdyh1x r-da5iq2 r-bztko3&quot;]/div[@class=&quot;css-901oao r-1vjbqqu r-t1w4ow r-ubezar r-majxgm r-135wba7 r-xyw6el r-q4m81j r-13qz1uu&quot;]</value>
      <webElementGuid>f0f637bc-ea5a-4bed-a8fb-ae806dd3d3bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div[2]/div/div[3]/div/div</value>
      <webElementGuid>2b492c4c-9c46-434a-bd9f-2bf03e71c6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Verification'])[1]/following::div[1]</value>
      <webElementGuid>c1523f2f-721c-444d-b73d-fe32224143a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[4]/following::div[4]</value>
      <webElementGuid>1ee17124-5714-474b-94ad-eea367435e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verification Code'])[1]/preceding::div[1]</value>
      <webElementGuid>2db4c87d-062e-4ae5-bf68-8f2a10dcfd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[6]</value>
      <webElementGuid>b826ca56-86c2-4ccf-80e0-b371e4ee27b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verification code has been sent to']/parent::*</value>
      <webElementGuid>f22611c0-869a-4e30-befc-e1e25ce7bd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[3]/div/div</value>
      <webElementGuid>28aa9d9e-41a8-4903-9be6-32289c182b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Verification code has been sent to 12345@gmail.com. Please insert verification code to verify.' or . = 'Verification code has been sent to 12345@gmail.com. Please insert verification code to verify.')]</value>
      <webElementGuid>b3962a5c-1d5c-4368-92d6-3754f7c57a12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
