<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sorry, there is an error in our system. Please try again after a while</name>
   <tag></tag>
   <elementGuidId>a61a28e4-2b43-4346-82df-58601dcd4b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[8]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08b20265-52e0-42a0-b378-1bfe410cca74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>5ff57c9f-1c7e-45f7-a52b-77484f38fb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-jwli3a r-t1w4ow r-ubezar r-majxgm r-135wba7 r-fdjqy7</value>
      <webElementGuid>4701fac7-b2a4-4591-9735-e30766c46a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[8]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-1yos0t3 r-1udh08x r-nsbfu8 r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-13awgt0 r-18u37iz r-1h0z5md&quot;]/div[@class=&quot;css-901oao r-jwli3a r-t1w4ow r-ubezar r-majxgm r-135wba7 r-fdjqy7&quot;]</value>
      <webElementGuid>e8cddbd0-3365-43b2-872a-ef5e919484fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div</value>
      <webElementGuid>d8f0b874-9c57-443c-87f8-1efe250ea9a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
