<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_kabuto</name>
   <tag></tag>
   <elementGuidId>e24498f5-f007-43f7-ac3b-f1852f6c4cf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.css-4rbku5.css-901oao.css-bfa6kz.r-t1w4ow.r-ubezar.r-b88u0q.r-rjixqe.r-fdjqy7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div/div/div/div/div[2]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>feb793bc-c63e-4116-a292-57079399cb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6ddcb96a-1c76-4162-85de-185cfee8aef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>63776771-5182-471b-b755-c299e8fdd343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>0d497415-ca0b-4514-bd85-bda4e672a6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4rbku5 css-901oao css-bfa6kz r-t1w4ow r-ubezar r-b88u0q r-rjixqe r-fdjqy7</value>
      <webElementGuid>5823cab5-4781-4fb0-b00c-54334c7b1a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>kabuto</value>
      <webElementGuid>f4f2dcf2-431d-4b39-b4d1-8a5cf8ced712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-1ihkh82&quot;]/div[@class=&quot;css-1dbjc4n r-1kihuf0 r-18u37iz r-16y2uox r-1wtj0ep r-15g7tld r-11c0sde r-nib5yn r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-cvk9hz&quot;]/div[@class=&quot;css-1dbjc4n r-1l31rp8 r-kdyh1x r-1phboty r-rs99b7 r-1udh08x r-1yzf0co&quot;]/div[@class=&quot;css-1dbjc4n r-qklmqi r-1l31rp8 r-1phboty r-5oul0u r-1l7z4oj r-ymttw5&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-1wbh5a2 r-1777fci&quot;]/h3[@class=&quot;css-4rbku5 css-901oao css-bfa6kz r-t1w4ow r-ubezar r-b88u0q r-rjixqe r-fdjqy7&quot;]</value>
      <webElementGuid>47e8d231-ad8c-4505-8a9a-b11534737c07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div/div/div/div/div[2]/h3</value>
      <webElementGuid>5b1b40e0-6d54-412a-9524-b40008badce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K'])[1]/following::h3[1]</value>
      <webElementGuid>78ca5ed8-116b-4984-9298-e61f2f5e95cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel Add-ons'])[1]/following::h3[1]</value>
      <webElementGuid>e9a95df8-bcdf-49fc-ac6d-377c1517dd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kabutominasan@gmail.com'])[1]/preceding::h3[1]</value>
      <webElementGuid>802be138-dd26-451d-8c02-7ed84aa9c19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Points'])[1]/preceding::h3[1]</value>
      <webElementGuid>ce0d5842-cf5f-4519-b074-7d9d60303f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='kabuto']/parent::*</value>
      <webElementGuid>a4eca966-8103-4242-ba41-f8d67efc4b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>200a5671-ed89-4893-9a5e-66fb86721a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'kabuto' or . = 'kabuto')]</value>
      <webElementGuid>40a5cada-cd58-4c04-90f3-3f34ccf9b877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
