<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm password_confirmed_password</name>
   <tag></tag>
   <elementGuidId>b73dd4d5-dc21-4e25-b006-d0783ade1d8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmed_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmed_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>435a1dc6-4545-4848-8076-c4e64a35e61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>83937f07-0edf-4ba5-a20a-72a20dc957cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmed_password</value>
      <webElementGuid>bac03759-4c4b-45ff-82cc-0f3b5516dabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ZMH9h0HCYH9GGNxHnXGJ</value>
      <webElementGuid>4ac41beb-1d53-4e81-a386-202f54dea879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm your password</value>
      <webElementGuid>10775f61-1e54-4bde-89a4-2914cb27e5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>877ba6b0-c684-4290-8892-1e2d49b446b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e0087b45-5411-4bdf-af34-7b748a3f42bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>655a20a8-9731-4cbe-b5a6-6b78dca82155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b8e9d464-0c03-4ae0-a351-53bb8e9e5f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1b1135c-5302-4125-b58e-e24e877e88e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga-action</name>
      <type>Main</type>
      <value>start typing</value>
      <webElementGuid>7e77bcd6-d045-4b10-b934-df89d957b0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga-label</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>94111e4b-51a6-4e0a-be6f-e884450f5099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmed_password</value>
      <webElementGuid>3933e26c-a46c-488f-a540-27f75d4ed20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Q</value>
      <webElementGuid>55fd6dd5-0c32-4981-9677-ee62ed3b375f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmed_password&quot;)</value>
      <webElementGuid>dadbbb93-7fe6-47b8-95c6-5d20bf385b99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmed_password']</value>
      <webElementGuid>d360a4c6-9666-43f4-b711-84cdfd6e3725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div/div/div/div/div/form/div[2]/div/div/div/div/input</value>
      <webElementGuid>5b46fdd0-0e9b-46f9-8f30-ab1400bd4651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>0bb65681-45f5-4f8b-88ed-5acd62d4e189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirmed_password' and @placeholder = 'Confirm your password' and @id = 'confirmed_password']</value>
      <webElementGuid>d00fd908-28ec-44f3-9c1c-ad6f48763511</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
