<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Facebook_gsi_1257_911575</name>
   <tag></tag>
   <elementGuidId>d692d1b0-ffad-4a45-809c-38f6b56789eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gsi_1257_911575</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_1257_911575']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>49dde021-ce57-429d-88e1-f8f24f18d3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?size=medium&amp;width=400&amp;client_id=909540881369-n0acgq130phqtg02m2ufk6fkei6ponor.apps.googleusercontent.com&amp;iframe_id=gsi_1257_911575&amp;as=zJwDkSl+XS5sHLTdvKAKzg</value>
      <webElementGuid>d0e3881f-7291-4989-990a-7e3071c96e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_1257_911575</value>
      <webElementGuid>bb5d8cdc-81e2-437b-abeb-f91c43225bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tombol Login dengan Google</value>
      <webElementGuid>2d41de29-f0e1-44e3-a34b-a6a2106bbea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_1257_911575&quot;)</value>
      <webElementGuid>257b6ec5-9c56-4244-a4e2-85515b541102</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_1257_911575']</value>
      <webElementGuid>68460c2f-5d53-4a22-9fb8-f7fe55d06138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='googleSignIn']/div/iframe</value>
      <webElementGuid>24a2d445-65ec-4c9d-acbc-29a7abcc0b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5a354d77-f39e-4f1a-b1c8-0a0d5ad4c995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?size=medium&amp;width=400&amp;client_id=909540881369-n0acgq130phqtg02m2ufk6fkei6ponor.apps.googleusercontent.com&amp;iframe_id=gsi_1257_911575&amp;as=zJwDkSl+XS5sHLTdvKAKzg' and @id = 'gsi_1257_911575' and @title = 'Tombol Login dengan Google']</value>
      <webElementGuid>dd727282-23f2-4c43-b904-3adab0a84581</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
