<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login dengan Google</name>
   <tag></tag>
   <elementGuidId>6ac77909-bc21-4d08-b45e-4f46ef053d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.nsm7Bb-HzV7m-LgbsSe-BPrWId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bdc105ae-0847-4930-9507-58fc36d3627f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nsm7Bb-HzV7m-LgbsSe-BPrWId</value>
      <webElementGuid>a271f7b9-625c-424c-bbf0-7f54f25e4c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login dengan Google</value>
      <webElementGuid>c829dc4d-a331-4391-a0d1-c629a23e1cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;nsm7Bb-HzV7m-LgbsSe  pSzOP-SxQuSe i5vt6e-Ia7Qfc uaxL4e-RbRzK&quot;]/div[@class=&quot;nsm7Bb-HzV7m-LgbsSe-bN97Pc-sM5MNb&quot;]/span[@class=&quot;nsm7Bb-HzV7m-LgbsSe-BPrWId&quot;]</value>
      <webElementGuid>71872e62-c6d8-4821-8454-9c2aa7db2326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAVBAR/REGISTER/Register with google/iframe_Facebook_gsi_1257_911575</value>
      <webElementGuid>112439d3-0cf0-4394-84a8-8d26b000b941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/span</value>
      <webElementGuid>a97d6477-5185-431b-9507-e9474f01b463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login dengan Google'])[2]/preceding::span[1]</value>
      <webElementGuid>e9817a11-42b7-40e6-afd7-38a4f784f831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login dengan Google']/parent::*</value>
      <webElementGuid>c7bea371-1a8b-481c-847d-8731f981eccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>28f94401-2986-4f8a-8544-b46c529024ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login dengan Google' or . = 'Login dengan Google')]</value>
      <webElementGuid>aedc3a7b-15fa-47e9-aeba-a006fd490547</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
