<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_March</name>
   <tag></tag>
   <elementGuidId>492c3824-6108-42b2-85c4-847af21c5a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='12-March']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#12-March > div.css-1dbjc4n.r-1awozwy.r-18u37iz.r-1w6e6rj.r-1h0z5md.r-ymttw5.r-oyd9sg.r-13qz1uu > div.css-901oao.css-bfa6kz.r-13awgt0.r-t1w4ow.r-ubezar.r-majxgm.r-135wba7.r-fdjqy7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96a680f0-9c0c-4ef5-8540-61853ffb1fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>6c02bf76-d337-478b-8b7f-accdc170f817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao css-bfa6kz r-13awgt0 r-t1w4ow r-ubezar r-majxgm r-135wba7 r-fdjqy7</value>
      <webElementGuid>16702f10-648c-4ca5-acc4-b9736ed17f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>March</value>
      <webElementGuid>c557c04d-7474-41e4-819f-0dfe39375613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;12-March&quot;)/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-1w6e6rj r-1h0z5md r-ymttw5 r-oyd9sg r-13qz1uu&quot;]/div[@class=&quot;css-901oao css-bfa6kz r-13awgt0 r-t1w4ow r-ubezar r-majxgm r-135wba7 r-fdjqy7&quot;]</value>
      <webElementGuid>120bc4e5-10ce-410a-98a1-84798aad1651</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='12-March']/div/div[2]</value>
      <webElementGuid>e761eb3c-396b-4fd0-abf8-e70c25952ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='February'])[1]/following::div[4]</value>
      <webElementGuid>e87f7282-7303-4db6-8b8e-4f12c9c29af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='January'])[1]/following::div[8]</value>
      <webElementGuid>e09a0492-f0cd-4c06-9f5c-d86a25433761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='April'])[1]/preceding::div[2]</value>
      <webElementGuid>291a778c-e2cc-4b83-b290-3320152cd826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May'])[1]/preceding::div[6]</value>
      <webElementGuid>69aaa58a-0c02-4262-a6e8-5ced27e23be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='March']/parent::*</value>
      <webElementGuid>89f8efa3-faa5-47cd-b0a1-30740b933740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/div/div[2]</value>
      <webElementGuid>ce09bf1a-bdde-4ba6-95d1-5f82676c908c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'March' or . = 'March')]</value>
      <webElementGuid>ab9b7a07-58b2-4d69-9d3a-b908ffe6907a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
