<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Done</name>
   <tag></tag>
   <elementGuidId>be1e9ae2-6c0b-4e2e-8a39-8b8f790d5930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-901oao.css-bfa6kz.r-jwli3a.r-t1w4ow.r-1o4mh9l.r-b88u0q.r-f0eezp.r-q4m81j</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94b9d399-dba6-4cdb-a508-e77a03602985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>1b4314e2-464c-4fb7-88a0-a9be38a30727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bba53ed0-8ff3-40dc-9f39-81014f71a6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao css-bfa6kz r-jwli3a r-t1w4ow r-1o4mh9l r-b88u0q r-f0eezp r-q4m81j</value>
      <webElementGuid>9ce4c656-e637-45b2-a264-205a5574f13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>fa37e57d-95ef-47fe-a1ba-592871252ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-1xcajam r-ipm5af r-1uzo8ef r-13qz1uu r-1s3egr7&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-14lw9ot r-kdyh1x r-1yos0t3 r-1jgb5lz r-r0h9e2 r-bztko3 r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-1wtj0ep r-wech8c r-mrxtjd r-1guathk r-oyd9sg r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1euycsn r-105ug2t r-u8s1d r-zchlnj r-j76wpu&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-b4qz5r r-1udh08x r-4k2abt r-1ep47lj r-1clhhh9 r-1ftll1t&quot;]/div[@class=&quot;css-1dbjc4n r-4k2abt r-1ep47lj r-1clhhh9 r-1ftll1t&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-5njf8e&quot;]/div[@class=&quot;css-1dbjc4n r-1q142lx r-1wtj0ep r-1e081e0&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-18t94o4 css-1dbjc4n r-naaltd r-kdyh1x r-oo3563 r-1loqt21 r-10paoce r-1e081e0 r-5njf8e r-1otgn73 r-lrvibr&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-13awgt0 r-18u37iz r-1777fci&quot;]/div[@class=&quot;css-901oao css-bfa6kz r-jwli3a r-t1w4ow r-1o4mh9l r-b88u0q r-f0eezp r-q4m81j&quot;]</value>
      <webElementGuid>56b162eb-eb67-4471-9f9b-ac209129d6b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>40c3020d-3a49-4c4c-bec2-8877e7e6b8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/following::div[2]</value>
      <webElementGuid>26241b25-e9a6-44d0-a872-e47abf2a6c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysian Ringgit'])[1]/following::div[5]</value>
      <webElementGuid>43f08c04-1b8b-456f-ae01-1df555178aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay'])[1]/preceding::div[1]</value>
      <webElementGuid>756d6ff0-9427-45f3-83f8-a1a26a8736d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/preceding::div[8]</value>
      <webElementGuid>a9f16a0f-1b13-4f57-b9eb-0afc8bda6eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>fb26529a-d815-4291-b070-5147c7ec7d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>e71e7007-30f2-4553-bf7c-2d433fa47a29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
